sudo: required
language: node_js
addons:
  chrome: stable
node_js:
- 8.11.3
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_ecafe84576f0_key -iv $encrypted_ecafe84576f0_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
- export PATH="$HOME/.meteor:$PATH"
- curl https://install.meteor.com | /bin/sh
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key.pem
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add .travis/deploy_key.pem
- ssh -i .travis/deploy_key.pem mariposas@staging.taturanamobi.com.br pwd
# deploy:
#   provider: script
#   script: bash deploy.sh production $TRAVIS_TAG
#   on:
#     tags: true
#     all_branches: true
