sudo: required
language: node_js

addons:
  chrome: stable

node_js:
- 8.11.3

cache:
  directories:
    - node_modules

before_install:
- export PATH="$HOME/.meteor:$PATH"
- curl https://install.meteor.com | /bin/sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"