sudo: required
language: node_js
dist: trusty
services:
  - docker
addons:
  chrome: stable
node_js:
- 8.16.2
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_ecafe84576f0_key -iv $encrypted_ecafe84576f0_iv -in taturana_key -out .travis/taturana_key -d
- export PATH="$HOME/.meteor:$PATH"
- curl https://install.meteor.com | /bin/sh
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success:
# - docker build -t taturanamobi/plataforma-frontend .
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# - docker push taturanamobi/plataforma-frontend
- eval "$(ssh-agent -s)"
- chmod 600 .travis/taturana_key
- echo -e "Host staging.taturanamobi.com.br\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh -i .travis/taturana_key mariposas@staging.taturanamobi.com.br "cd Code/plataforma-frontend/ && git fetch && git checkout $TRAVIS_COMMIT"
- ssh -i .travis/taturana_key mariposas@staging.taturanamobi.com.br docker-compose -f Code/plataforma-frontend/docker-compose.staging.yml pull
- ssh -i .travis/taturana_key mariposas@staging.taturanamobi.com.br docker-compose -f Code/plataforma-frontend/docker-compose.staging.yml down
- ssh -i .travis/taturana_key mariposas@staging.taturanamobi.com.br docker-compose -f Code/plataforma-frontend/docker-compose.staging.yml up -d
- ssh -i .travis/taturana_key mariposas@staging.taturanamobi.com.br docker-compose -f Code/plataforma-frontend/docker-compose.staging.yml up --build --force-recreate -d frontend
# deploy:
#   provider: script
#   script: bash deploy.sh production $TRAVIS_TAG
#   on:
#     tags: true
#     all_branches: true
