version: '2'

networks:
  taturana:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 11.0.0.10/8

volumes:
  # redis_data:
  #   driver: local
  s3_data:
    driver: local
  mongo_data:
    driver: local
  local_postgres_data:
    driver: local
  portainer-data:
    driver: local
  mariadb:
    driver: local
  wordpress:
    driver: local

services:
  mongo:
    extends:
      file: docker-compose.yml
      service: mongo
    networks:
      taturana:

  # redis:
  #   extends:
  #     file: docker-compose.yml
  #     service: redis
  #   networks:
  #     taturana:

  fake-smtp:
    extends:
      file: docker-compose.yml
      service: fake-smtp
    environment:
      MH_HOSTNAME: fake-smtp.stag.taturanamobi.com.br
    networks:
      taturana:
    labels:
      traefik.frontend.rule: Host:fake-smtp.stag.taturanamobi.com.br
      traefik.port: '8025'
      traefik.enable: 'true'

  traefik:
    extends:
      file: docker-compose.yml
      service: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.staging.toml:/etc/traefik/traefik.toml
      - ./acme.staging.json:/acme.json
    networks:
      taturana:
    labels:
      traefik.frontend.rule: Host:traefik.stag.taturanamobi.com.br
      traefik.port: '8080'
      traefik.enable: 'true'

  images:
    extends:
      file: docker-compose.yml
      service: images
    networks:
      taturana:
    labels:
      traefik.frontend.rule: Host:images.stag.taturanamobi.com.br
      traefik.enable: 'true'
      traefik.port: '9000'

  postgres:
    build:
      context: ../plataforma-v2/docker
      dockerfile: ./production/postgres/Dockerfile
    image: dev_db
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: taturana
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
    networks:
      taturana:
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

  # minio:
  #   image: minio/minio
  #   environment:
  #     MINIO_ACCESS_KEY: admin
  #     MINIO_SECRET_KEY: password
  #   volumes:
  #   - s3_data:/data
  #   ports:
  #   - 4000:9000/tcp
  #   networks:
  #     taturana:
  #   command:
  #   - server
  #   - /data
  #   labels:
  #     traefik.frontend.rule: Host:minio.stag.taturanamobi.com.br
  #     traefik.port: '9000'
  #     traefik.enable: 'true'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #   - 4004:8080
  #   networks:
  #     taturana:
  #   labels:
  #     traefik.frontend.rule: Host:adminer.stag.taturanamobi.com.br
  #     traefik.port: '8080'
  #     traefik.enable: 'true'

  metabase:
    image: metabase/metabase
    environment:
      JAVA_TIMEZONE: America/Sao_Paulo
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: '5432'
      MB_DB_USER: debug
      MB_DB_PASS: debug
      MB_DB_HOST: postgres
    depends_on:
    - postgres
    ports:
    - 4006:3000/tcp
    networks:
      taturana:
    labels:
      traefik.frontend.rule: Host:relatorios.stag.taturanamobi.com.br
      traefik.enable: 'true'
      traefik.port: '3000'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4005:8081
    networks:
      taturana:
    labels:
      traefik.frontend.rule: Host:mongo-express.stag.taturanamobi.com.br
      traefik.port: '8081'
      traefik.enable: 'true'

  portainer:
    image: portainer/portainer
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ports:
      - 9000
    networks:
      taturana:
    labels:
      traefik.frontend.rule: Host:portainer.stag.taturanamobi.com.br
      traefik.port: '9000'
      traefik.enable: 'true'

  frontend:
    image: taturanamobi/plataforma-frontend
    ports:
      - 3000:3000
    networks:
      taturana:
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - "./uploads:/opt/meteor/dist/bundle/uploads"
    environment:
      - ROOT_URL=https://stag.taturanamobi.com.br
      - MONGO_URL=mongodb://mongo:27017/taturana
      - MAIL_URL=smtp://fake-smtp:1025
      - WORKER=1
    labels:
      traefik.frontend.rule: Host:stag.taturanamobi.com.br
      traefik.port: '3000'
      traefik.enable: 'true'

  # container-crontab:
  #   privileged: true
  #   image: rancher/container-crontab:v0.3.0
  #   environment:
  #     DOCKER_API_VERSION: '1.24'
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - mariadb:/bitnami
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    environment:
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wordpress:/bitnami
    labels:
      traefik.frontend.rule: Host:portfolio.stag.taturanamobi.com.br
      traefik.enable: 'true'
      traefik.port: '3000'
