version: '3'

volumes:
  # redis_data:
  #   driver: local
  # fileshare_data:
  #   driver: local
  elk_data:
    driver: local
  s3_data:
    driver: local
  mongo_data:
    driver: local
  local_postgres_data:
    driver: local
  portainer_data:
    driver: local
  mariadb:
    driver: local
  wordpress:
    driver: local

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017/tcp
    volumes:
      - mongo_data:/data/db
      - ./backups:/backups
    environment:
      MONGO_INITDB_DATABASE: taturana

  # redis:
  #   extends:
  #     file: docker-compose.yml
  #     service: redis
  #   networks:
  #     taturana:

  fake-smtp:
    image: mailhog/mailhog
    restart: always
    environment:
      MH_HOSTNAME: fake-smtp.taturana
    ports:
    - 1025/tcp
    - 8025/tcp
    environment:
      MH_HOSTNAME: fake-smtp.stag.taturanamobi.com.br
    labels:
      traefik.frontend.rule: Host:fake-smtp.stag.taturanamobi.com.br
      traefik.port: '8025'
      traefik.enable: 'true'

  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - 80:80/tcp
      - 8080/tcp
      - 443:443/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.staging.toml:/etc/traefik/traefik.toml
      - ./acme.staging.json:/acme.json
    labels:
      traefik.frontend.rule: Host:traefik.stag.taturanamobi.com.br
      traefik.port: '8080'
      traefik.enable: 'true'

  images:
    image: h2non/imaginary
    restart: always
    ports:
    - 9000/tcp
    volumes:
      - ./uploads:/uploads
    command:
    - -http-cache-ttl
    - '10080'
    - -cors
    - -gzip
    - -concurrency
    - '10'
    - -enable-url-source
    - -mount
    - /uploads
    labels:
      traefik.frontend.rule: Host:images.stag.taturanamobi.com.br
      traefik.enable: 'true'
      traefik.port: '9000'

  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #   - 9000/tcp
  #   environment:
  #     POSTGRES_DB: taturana
  #     POSTGRES_USER: debug
  #     POSTGRES_PASSWORD: debug
  #   volumes:
  #     - local_postgres_data:/var/lib/postgresql/data

  # minio:
  #   image: minio/minio
  #   environment:
  #     MINIO_ACCESS_KEY: admin
  #     MINIO_SECRET_KEY: password
  #   volumes:
  #   - s3_data:/data
  #   ports:
  #   - 4000:9000/tcp
  #   networks:
  #     taturana:
  #   command:
  #   - server
  #   - /data
  #   labels:
  #     traefik.frontend.rule: Host:minio.stag.taturanamobi.com.br
  #     traefik.port: '9000'
  #     traefik.enable: 'true'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #   - 4004:8080
  #   networks:
  #     taturana:
  #   labels:
  #     traefik.frontend.rule: Host:adminer.stag.taturanamobi.com.br
  #     traefik.port: '8080'
  #     traefik.enable: 'true'

  # metabase:
  #   image: metabase/metabase
  #   restart: always
  #   environment:
  #     JAVA_TIMEZONE: America/Sao_Paulo
  #     MB_DB_TYPE: postgres
  #     MB_DB_DBNAME: metabase
  #     MB_DB_PORT: '5432'
  #     MB_DB_USER: debug
  #     MB_DB_PASS: debug
  #     MB_DB_HOST: postgres
  #   depends_on:
  #   - postgres
  #   ports:
  #   - 3000/tcp
  #   labels:
  #     traefik.frontend.rule: Host:relatorios.stag.taturanamobi.com.br
  #     traefik.enable: 'true'
  #     traefik.port: '3000'

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081/tcp
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: taturanastaging
  #   labels:
  #     traefik.frontend.rule: Host:mongo-express.stag.taturanamobi.com.br
  #     traefik.port: '8081'
  #     traefik.enable: 'true'

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      traefik.frontend.rule: Host:portainer.stag.taturanamobi.com.br
      traefik.port: '9000'
      traefik.enable: 'true'

  frontend:
    image: taturanamobi/plataforma-frontend
    restart: always
    build: .
    ports:
      - 3000/tcp
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - "./uploads:/opt/meteor/dist/bundle/uploads"
    environment:
      - ROOT_URL=https://stag.taturanamobi.com.br
      - MONGO_URL=mongodb://mongo:27017/taturana
      - MAIL_URL=smtp://fake-smtp:1025
      - PORT=3000
      - WORKER=0
      - 'METEOR_SETTINGS={"public": {"imageServerUrl": "https://images.stag.taturanamobi.com.br", "analyticsSettings": {"Google Analytics": {"trackingId": "UA-119536431-1"}}}}'
    labels:
      traefik.frontend.rule: Host:stag.taturanamobi.com.br
      traefik.port: '3000'
      traefik.enable: 'true'

  # cleanup:
  #   image: meltwater/docker-cleanup:1.8.0
  #   environment:
  #     CLEAN_PERIOD: '3600'
  #     DEBUG: '0'
  #     DELAY_TIME: '900'
  #     KEEP_CONTAINERS: '*:*'
  #     KEEP_CONTAINERS_NAMED: '*_data'
  #     KEEP_IMAGES: rancher/
  #     LOOP: 'true'
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock

  # elk:
  #   image: sebp/elk
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"
  #   volumes:
  #     - elk_data:/var/lib/elasticsearch
  #   networks:
  #     taturana:
  #   labels:
  #     traefik.frontend.rule: Host:kibana.stag.taturanamobi.com.br
  #     traefik.port: '5601'
  #     traefik.enable: 'true'

  # container-crontab:
  #   privileged: true
  #   image: rancher/container-crontab:v0.3.0
  #   environment:
  #     DOCKER_API_VERSION: '1.24'
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock

  # fileshare:
  #   image: psitrax/psitransfer
  #   ports:
  #     - "3333:3000"
  #   volumes:
  #     - fileshare_data:/data
  #   networks:
  #     taturana:
  #   labels:
  #     traefik.frontend.rule: Host:fileshare.stag.taturanamobi.com.br
  #     traefik.port: '3000'
  #     traefik.enable: 'true'

  # mariadb:
  #   image: 'bitnami/mariadb:latest'
  #   restart: always
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MARIADB_USER=bn_wordpress
  #     - MARIADB_DATABASE=bitnami_wordpress
  #   volumes:
  #     - mariadb:/bitnami
  # wordpress:
  #   image: bitnami/wordpress:latest
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - 80/tcp
  #     - 443/tcp
  #   environment:
  #     - WORDPRESS_DATABASE_USER=bn_wordpress
  #     - WORDPRESS_DATABASE_NAME=bitnami_wordpress
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - wordpress:/bitnami
  #   labels:
  #     traefik.frontend.rule: Host:portfolio.stag.taturanamobi.com.br
  #     traefik.enable: 'true'
  #     traefik.port: '80'
