# docker-compose.yml

app:
  # image: taturanamobi/plataforma-frontend
  build: .
  ports:
    - "80:3000"
  links:
    - mongo
  volumes:
    - "$PWD:/opt/meteor/src"
  environment:
    - ROOT_URL=http://taturanamobi
    - MONGO_URL=mongodb://mongo:27017/meteor

mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
