version: '3'

# networks:
#   taturana:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#       - subnet: 11.0.0.10/8
#
volumes:
  redis_data:
    driver: local
  s3_data:
    driver: local
  mongo_data:
    driver: local
  local_postgres_data:
    driver: local

services:
  mongo:
    # image: mongo
    # image: docker.io/bitnami/mongodb:6.0
    image: registry.gitlab.com/tozd/docker/meteor-mongodb:6.0
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/bitnami/mongodb
      - ./backups:/backups
      - ./run.config:/etc/service/mongod/run.config
    environment:
      - MONGO_INITDB_DATABASE=taturana
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest # that's safe

  fake-smtp:
    image: mailhog/mailhog
    environment:
      MH_HOSTNAME: fake-smtp.taturana
    ports:
    - 1025:1025/tcp
    - 4001:8025/tcp
    labels:
      traefik.frontend.rule: Host:fake-smtp.taturana
      traefik.port: '8025'
      traefik.enable: 'true'
      traefik.acme: 'false'

  traefik:
    image: traefik:1.7-alpine
    ports:
      - 80:80/tcp
      - 4002:8080/tcp
      - 443:443/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      traefik.frontend.rule: Host:traefik.taturana
      traefik.port: '8080'
      traefik.enable: 'true'
      traefik.acme: 'false'

  images:
    image: h2non/imaginary
    stdin_open: true
    tty: true
    ports:
    - 4003:9000/tcp
    volumes:
      - ./uploads:/uploads
    command:
    - -cors
    - -gzip
    - -concurrency
    - '10'
    - -enable-url-source
    - -mount
    - /uploads
    labels:
      traefik.frontend.rule: Host:images.taturana
      traefik.enable: 'true'
      traefik.port: '9000'
      traefik.acme: 'false'



  mongo-express:
    image: mongo-express
    # restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://meteor:taturanamobi2023@mongo:27017/meteor
    ports:
      - 4005:8081
    labels:
      traefik.frontend.rule: Host:mongo-express.taturana
      traefik.port: '8081'
      traefik.enable: 'true'
      traefik.acme: 'false'
